//------------------------------------------------------------------------------
// u-robot Digital Controller Firmware
//------------------------------------------------------------------------------

#include <stdio.h>
#include <time.h>
#include <rt_misc.h>
#include <stdlib.h>
#include "Memory_map.h"
#include "Memory_Map_BLE.h"
#include "Int_Handlers.h"
#include "rf_global_vars.h"
#include "bucket_o_functions.h"

#define BIT_MASK(n) ((1 << (n)) - 1)

#define IS_USING_GPIOS_FOR_TESTING 1

extern char send_packet[127];

unsigned int ASC[38] = {0};

int val2M = 19; //15
int cal_iteration = 0;
int LC_code = 0;

//////////////////////////////////////////////////////////////////
// Main Function
//////////////////////////////////////////////////////////////////

void my_delay(void) {
	uint32_t timer = 0;
	while (timer < 900000) {
	  timer++;
	}
}

uint16_t write_bitfield(uint16_t prev_data, uint16_t lsb, uint16_t numbits, uint16_t data) {
	uint16_t prev_bitfield_mask = ~(BIT_MASK(numbits)<<lsb);
	uint16_t new_bitfield = prev_data & prev_bitfield_mask;
	new_bitfield = new_bitfield | (data<<lsb);
	return new_bitfield;
}

int main(void) {
	initialize_ASC();
	
	uint32_t gpio_address = (uint32_t)GPIO_REG__OUTPUT_PTR;
	
	uint16_t prev_data_bits = 0x0; // TODO DB: the default GPIO settings. There's code below which uses the prev_data_bits and _only_ overwrites the one data bit we're trying to toggle
	uint32_t data_address = gpio_address;

#if IS_USING_GPIOS_FOR_TESTING
	uint16_t data_bit_position = 1; // TODO DB: replace this with the bit position of the GPIO you're using (0-indexed)
#endif

	// Generate bitfields for writing a "0" or "1" without overwriting bits which were already written to the register
	uint16_t data_1 = write_bitfield(prev_data_bits, data_bit_position, 1, 1);
	uint16_t data_0 = write_bitfield(prev_data_bits, data_bit_position, 1, 0);


	while(1) {
		__asm (
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_1, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
			"STR data_0, 	[gpio_address];"
			"NOP;"
		);
	}

	return 0 ;
}


